name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: cd sgds-angular && npm run build:component && npm run build:prod
      - name: Version Check
        uses: EndBug/version-check@v2.1.0
        id: check
        with:
          file-name: ./sgds-angular/package.json
      - run: npm publish --tag latest ./sgds-angular
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
